PackageName: "NLPModelsKnitro"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "bec4dd0d-7755-52d5-9a02-22f0ffc7efcb"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "v0.13.0"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
